### ISSUE TITLE
Improve reliability of presence detection (in uProxy)

### ISSUE THREAD

**Issue by agallant** [freedomjs/freedom-social-wechat#3]
Right now users broadcast their online status when they login - this can lead to a state where one user sees the other as online but not vice-versa (e.g. Alice signs in while Bob is offline, then Bob signs in).

Fix should be fairly straightforward - when Bob signs in and broadcasts ("pings") Alice his presence, she should respond ("pong") that she is online as well.

Additionally, when Alice logs out of uProxy, Bob still sees her as online - we need to broadcast logout status changes as well.

**Comment by agallant** [comment]
Possible workaround (from demo meeting) - just assume users are online, and send "ack" when there is an attempt to start a connection (no ack -> actually offline). The advantage is this approach could live better in the uProxy layer, the disadvantage is it's not the best user experience (though it may be acceptable).

The better user experience would be regular heartbeats, but the disadvantage here is it would be best done at the freedom layer and thus would potentially require rethinking encryption/obfuscation (and regardless of obfuscation, regular hidden messages, even probabilistic/Poisson, may look suspicious).

One last variable - switching to the "social2" (private/invite mode) API may also mitigate/change this issue.

**Comment by bemasc** [comment]
For efficiency, it might make sense to say:
1. If I receive a message from a remote peer, I must send a message back within 10 seconds, unless I've sent a message to that peer within the preceding 10 seconds.  The message I send may be semantically null.
2. If I send a message to a peer from whom I haven't received a message in the last 20 seconds, and I do not get any message back within 20 seconds, then that peer is offline.

This can be implemented entirely within the social provider, and should make the number of extra messages very small.

**Comment by masq** [comment]
The reason I'm hesitant to do heartbeats is due to high (obvious) amounts of network activity. I like your suggestions, @bemasc. But you gave me an idea which takes it a few steps further. Essentially, it will look like:

   • Bob logs in, sending a ping to his contacts indicating so.
   • Alice logs in, sending a ping to her contacts indicating so
   • Bob now can see Alice has come online, and since Alice's availability has changed, Bob sends a pong back to Alice
   • Both users can now see each other online.

In the case that a given contact, e.g. Alice, has multiple contacts, they would each pong back to her essentially simultaneously which is a bit loud/obvious, but there would be no need for constant heartbeats.
I've not pushed my local changes lately but I've implemented a change which should register (ping) a contact as being offline now [to their contacts].

**Comment by agallant** [comment]
Closing as deprecated (AFAIK, this module is essentially too unreliable due to changes on the wechat side).
