### ISSUE TITLE
userId not set correctly

### ISSUE THREAD

**Issue by dborkan** [freedomjs/freedom-social-wechat#5]
We are seeing that the userId is not set correctly:
- in onUserProfile events it is always "" (empty string) for all users
- in onClientState events it is always "0", for all clients

This is causing some problems for uProxy since we use the userId as a key in many of our mappings, like:
- we have errors because we get an onClientState for userId="0" but think that user has no profile (the profile came in but for userId="")
- if I get an onUserProfile for my friend Alice, then another one for my friend Bob, Bob's info will overwrite Alice since they both have the same userId

We need to set userId to something that will be constant for a given WeChat account.  Could we use the UserName field here?  Or is there some other field like the profile image which remains constant?  

Earlier today we discussed concatenating fields like address, but if those fields changed and the userId changed as a result, it would also cause bugs in uProxy (e.g. we would display 2 entries on the buddylist for that user, one for the old userId and another for the new userId)

**Comment by dborkan** [comment]
Testing more, it seems like UserName is not a constant field.  For example here is the value for 2 login attempts, both for the same "Sam Pro" user:

```
{"Uin":0,"UserName":"@372a6267fcee77846329fe30e3d6436d774f3f36c53c6bae2c9d02ad920f2c99","NickName":"Sam Pro","HeadImgUrl":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=634790094&username=@372a6267fcee77846329fe30e3d6436d774f3f36c53c6bae2c9d02ad920f2c99&skey=@crypt_2591e7ed_5337b5acc1c22e1a8be160c35f03ee04","ContactFlag":3,"MemberCount":0,"MemberList":[],"RemarkName":"","HideInputBarFlag":0,"Sex":0,"Signature":"Allthesocialnetworks","VerifyFlag":0,"OwnerUin":0,"PYInitial":"SAMPRO","PYQuanPin":"SamPro","RemarkPYInitial":"","RemarkPYQuanPin":"","StarFriend":0,"AppAccountFlag":0,"Statues":0,"AttrStatus":233477,"Province":"","City":"","Alias":"","SnsFlag":0,"UniFriend":0,"DisplayName":"","ChatRoomId":0,"KeyWord":"","EncryChatRoomId":""}
```

and

```
{"Uin":0,"UserName":"@ef8cd7c9431806492ef58f47aa4bca65fc4699608e931a1fd80c108291bc3baf","NickName":"Sam Pro","HeadImgUrl":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=634790094&username=@ef8cd7c9431806492ef58f47aa4bca65fc4699608e931a1fd80c108291bc3baf&skey=@crypt_2591e7ed_c62ef21ff6d7cf1066e84d7869eba560","ContactFlag":3,"MemberCount":0,"MemberList":[],"RemarkName":"","HideInputBarFlag":0,"Sex":0,"Signature":"Allthesocialnetworks","VerifyFlag":0,"OwnerUin":0,"PYInitial":"SAMPRO","PYQuanPin":"SamPro","RemarkPYInitial":"","RemarkPYQuanPin":"","StarFriend":0,"AppAccountFlag":0,"Statues":0,"AttrStatus":233477,"Province":"","City":"","Alias":"","SnsFlag":0,"UniFriend":0,"DisplayName":"","ChatRoomId":0,"KeyWord":"","EncryChatRoomId":""}
```

It might be worth looking into what the `AttrStatus` field is - I see it is consistently 233477 for Sam Pro everytime, and my one other contact has a different, also consistent value.  Maybe we could concat this with the NickName to form a more-unique ID?

**Comment by masq** [comment]
This was a somewhat recent change by wechat (maybe a month, month and a half at this point) where they don't send down the Uin of a contact (what we had been using as the UserId), and instead just send down 0. I agree, this is causing errors, and there are a couple of ways I have thought about on how to go about getting around this that i mentioned in the meeting. 

One such way is to use multiple fields and concat them, like you suggested. The problem with this, is that most fields are subject to change, and the ones that aren't are consistent across ALL users (that I've seen). This would cause issues if/when a given user changes their status, or username, or whatever. 

Another way that I've noticed (haven't tested in a little while, wechat could have stripped the Uins from this) is by getting contacts contained in group messages -- the Uin's of users are still sent down to clients through that method. This is interesting because in social1 you could add all contacts to a group chat, and then delete the group chat; the disadvantage to this is possibly some notification on users devices indicating them that they were removed from a chat, however, this would need to be further tested. I might be able to make it so there is no notification that this has happened. In social2, this works really well, since my current method for doing invites would be to create a group chat between two users and call it "uproxy <username>" for each person that accepts the invite. In which case, on login I would just look for groups that have names prefixed with "uproxy " and then fetch the contact list for those groupchats, which gives us the userIds for all of the relevant contacts in a person's wechat contacts.

There is another third way I can think of, and that honestly might be the way to go. Essentially, there is notification data sent out in messages upon login, message send, etc. Upon login, a message is send out to users using a value that isn't in their JSON blob. I'll have to investigate this more in the future to determine viability (consistency between contact state change, session, etc.).

<user>.UserName is what we are currently using for the clientId. This value changes every time you login.

I'm not actually sure what <user>.AttrStatus represents, but it does have collisions over a larger contact list. I've tested and found that two different contacts will sometimes have the same value (although, I've not noticed it change between sessions, but I've not looked too hard at that field).

**Comment by bemasc** [comment]
We could also just make the userId a locally generated unique token per-device, stored in local storage and communicated between social-quiver instances in-band.  It's not exactly the behavior we want but at least it's consistent and non-colliding.

**Comment by dborkan** [comment]
Do we at least get the unique id for the logged in user?  If so maybe users could send that to each other?  In that case we might only want to support ONLINE clients, not ONLINE_WITH_OTHER_APP (we wouldn't know their unique ids).

I'm also fine with the other solutions proposed.  Ben's solution is pretty similar to what we would be doing for Quiver.  Although some downsides of this are:
- Users who are signed into WeChat from different devices would end up with different IDs, and so uProxy would treat them as separate users (they would need to be permissioned again).
- Users might be able to spoof a friends ID (if Bob knows Alice's ID, Bob could claim that's also his ID and get the same uProxy permissions granted to Alice).

I'm thinking for now I will create a pull request that just uses the NickName for the userId.  This is far from ideal (in case the nickname changes or collides) but will at least allow us to due more testing in uProxy for the rest of the WeChat functionality.

**Comment by masq** [comment]
I'm currently investigating the third way i mentioned above, it seems promising. The second way doesn't work anymore, they've stripped the Uin from there as well. 

We do get the Uin of the logged in user, and so we could pass them between users; I think that would be a good solution if my current idea doesn't pan out. 

The quiver-like solution would be alright, but there would be those problems, but I also worry about unique tokens being generated randomly client side having collisions. For example, if Alice generates her token, and then bob generates the same token (highly unlikely, but bob doesn't know Alice is using that token) and then Eve friends Alice and Bob, confusion ensues. This is similar to the latter concern @dborkan brought up.

I've accepted the PR, I think that is a good temporary solution.

**Comment by lucyhe** [comment]
Is this resolved now that you've added wxids?

**Comment by masq** [comment]
Yes this should be marked as resolved.

On Nov 11, 2015, at 7:28 PM, lucyhe <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this resolved now that you've added wxids?

##
