### ISSUE TITLE
Logging into freedom-social-wechat creates a "File Transfer" chat

### ISSUE THREAD

**Issue by dborkan** [freedomjs/freedom-social-wechat#6]
See screenshot from my phone.  This "File Transfer" chat appears to have been created by logging into freedom-social-wechat.  Each time I log in again the timestamp updates.  Clicking on "File Transfer" shows an empty chat window.  We should try to remove this if possible (good news is that it hasn't resulted in any notifications on my phone, just looks weird in the chat tab of WeChat).

![wechat](https://cloud.githubusercontent.com/assets/6494307/10348395/e0039e1e-6d06-11e5-81dd-0695697bf1d6.png)

**Comment by masq** [comment]
This might actually just be a symptom of the wechat freedom module leveraging wechat's web interface itself, which has the file transfer agent automatically added to your contact list when you use it. If that is the reason, there isn't really anything that can be done about it, besides manually removing it from your contacts list (although i imagine it would show back up next time you used the wechat freedom module, or wechat's web interface). 

A good way to verify that this is the problem is by
    • deleting the file tranfer agent contact from your contacts list
    • going to web2.wechat.com and logging in
    • see if same issue occurs

The file transfer agent's main purpose is to provide a simple way to transfer files from your mobile to your other device. Unfortunately, I believe this is just a side-effect of using the webclient.

**Comment by agallant** [comment]
Documented as a known issue - https://github.com/freedomjs/freedom-social-wechat/commit/d672ffede8989a0b9ef2d73fdc58af246aefebe0
